### ISSUE TITLE
김민주: <feature> Add page 'Lobby' 

### ISSUE THREAD

**Issue by roses16-dev** [HangHae-TheFinalProject/FrontEnd#2]
### Need to : 
Lobby page 및 이를 이루는 컴포넌트 추가

**Comment by roses16-dev** [comment]
@keepfall @cherrydding 
참여 인원수 ( ex: 2/8 ) 표시랑 Public 방인지, password가 필요한 방인지 표시가 필요할 것 같아요!
와이어 프레임 때 따로 협의되지 않았는데 혹시 아이디어 있으신가요 !!

**Comment by keepfall** [comment]
참여 인원수와 공개 비공개 표시는 방 제목 앞에 나온다면 좋을거 같아요! ( ex: 자물쇠아이콘..?(on,off) (6/8) 방이름)
그리고 공개 비공개를 따로 설정을 하기 보다는 방 비밀번호를 입력하지 않는다면, 공개방으로 만들어지는 식으로도 가능할까요?

**Comment by roses16-dev** [comment]
2022/11/09 아침회의
 - Room 이미지 내 자물쇠 아이콘과 ( n / 8 ) 로 비밀방 여부, 참여중인 인원 수 표시하기로 함.
 - 지희님 의견에 따라 변동될 가능성 있음.

**Comment by roses16-dev** [comment]
PR #3
